spring:
  application:
    name: livechat
  mongodb:
    auto-index-creation: true
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:27017}
    database: ${DB:livechat}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    authentication-database: ${DB_AUTH:admin}
oauth:
  github:
    client:
      id: ${GITHUB_CLIENT_ID:ghci}
      secret: ${GITHUB_CLIENT_SECRET:ghcs}
